{% set version = "7.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-simplevis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/simplevis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/simplevis/simplevis_{{ version }}.tar.gz
  sha256: e8c8c3497c5f42e5383c2ab03c10da8dbcc5782b9770c32cb07b03e18e9d50b0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-htmlwidgets
    - r-leafem
    - r-leaflet
    - r-leafpop
    - r-lubridate
    - r-magrittr
    - r-plotly
    - r-purrr
    - r-rlang
    - r-santoku
    - r-scales
    - r-sf
    - r-shiny
    - r-snakecase
    - r-stars
    - r-stringr
    - r-tidyr
    - r-tidyselect
    - r-viridis
  run:
    - r-base
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-htmlwidgets
    - r-leafem
    - r-leaflet
    - r-leafpop
    - r-lubridate
    - r-magrittr
    - r-plotly
    - r-purrr
    - r-rlang
    - r-santoku
    - r-scales
    - r-sf
    - r-shiny
    - r-snakecase
    - r-stars
    - r-stringr
    - r-tidyr
    - r-tidyselect
    - r-viridis

test:
  commands:
    - $R -e "library('simplevis')"           # [not win]
    - "\"%R%\" -e \"library('simplevis')\""  # [win]

about:
  home: https://StatisticsNZ.github.io/simplevis/, https://github.com/StatisticsNZ/simplevis/
  license: MIT
  summary: Wrapper functions around the amazing 'ggplot2' and 'leaflet' packages that aims to simplify beautiful 'ggplot2' and 'leaflet' visualisation. Precursor package to the 'ggblanket' package.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
